### ISSUE TITLE
Named entity recognition

### ISSUE THREAD

**Issue by Sugandh81** [saayam-for-all/ai#6]
Named entity recognition task to get the information from the request

**Comment by RaoBhethanabotla** [comment]
Sugandha did a demo of sentiment analysis Ollama. Now you want to move that Langchain based technology.

ETA demo with Langchain ?

**Comment by RaoBhethanabotla** [comment]
Planning on doing a demo today.

**Comment by Sugandh81** [comment]
Demo is done. Currently on hold.
