### ISSUE TITLE
Implement DuckDuckGo search with LangChain

### ISSUE THREAD

**Issue by sanskriti-motwani** [saayam-for-all/ai#8]

**Comment by sanskriti-motwani** [comment]
Monday:
- Connected with Sugandha to understand the process of creating and utilizing Hugging Face API tokens.
- Integrated DuckDuckGo search functionality with a GPT model

Tuesday:
- Prepared the current model for demo

Next steps: modify and optimize the model based on feedback received during the demo.

**Comment by shaikmdsohail94** [comment]
Tuesday - 09/03/2024- Presented the Demo about Integrated DuckDuckGO with Hugging Face API and will be taking next steps in the coming days.

**Comment by sanskriti-motwani** [comment]
Next Steps:

1. Implement user input for the search query.
2. Filter out unnecessary information from the search results.
3. Handle long text input to avoid truncated responses.
4. Tune the model's parameters for better performance.
5. Experiment with other models for comparison.
